## Loading Data using pandas

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('pokemon_data.csv')

In [3]:
df.head(5) #prints the first 5 rows

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [4]:
df.tail(5) #prints the last 5 rows

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### Loading text data with comma separated text

In [10]:
df_txt=pd.read_csv('pokemon_data.csv',delimiter=',')

In [11]:
df_txt.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

## Reading Data

In [12]:
df.columns #reading headers

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [13]:
df['Name'] #reading each column

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [15]:
df[['Name','Type 2','HP']] #reading multiple columns

                      Name  Type 2  HP
0                Bulbasaur  Poison  45
1                  Ivysaur  Poison  60
2                 Venusaur  Poison  80
3    VenusaurMega Venusaur  Poison  80
4               Charmander     NaN  39
..                     ...     ...  ..
795                Diancie   Fairy  50
796    DiancieMega Diancie   Fairy  50
797    HoopaHoopa Confined   Ghost  80
798     HoopaHoopa Unbound    Dark  80
799              Volcanion   Water  80

[800 rows x 3 columns]

In [17]:
df[['Name','Type 2','HP']][0:6] #reading multiple columns from row 0 to row 5

                    Name  Type 2  HP
0              Bulbasaur  Poison  45
1                Ivysaur  Poison  60
2               Venusaur  Poison  80
3  VenusaurMega Venusaur  Poison  80
4             Charmander     NaN  39
5             Charmeleon     NaN  58

In [18]:
df.iloc[0] #reading row 0

#                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object

In [19]:
df.iloc[796:] #reading multiple rows

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [22]:
df.iloc[799,1] #reading object at a specific position

'Volcanion'

In [24]:
df.loc[df['Type 1']=='Psychic'] #reading specific row entities

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
69,64,Kadabra,Psychic,NaN,40,35,30,120,70,105,1,False
70,65,Alakazam,Psychic,NaN,55,50,45,135,95,120,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,1,False
104,96,Drowzee,Psychic,NaN,60,48,45,43,90,42,1,False
105,97,Hypno,Psychic,NaN,85,73,70,73,115,67,1,False
131,122,Mr. Mime,Psychic,Fairy,40,45,65,100,120,90,1,False
162,150,Mewtwo,Psychic,NaN,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,1,True
165,151,Mew,Psychic,NaN,100,100,100,100,100,100,1,False
191,177,Natu,Psychic,Flying,40,50,45,70,45,70,2,False
192,178,Xatu,Psychic,Flying,65,75,70,95,70,95,2,False
211,196,Espeon,Psychic,NaN,65,65,60,130,95,110,2,False
216,201,Unown,Psychic,NaN,48,72,48,72,48,48,2,False
217,202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False
269,249,Lugia,Psychic,Flying,106,90,130,90,154,110,2,True
271,251,Celebi,Psychic,Grass,100,100,100,100,100,100,2,False
303,280,Ralts,Psychic,Fairy,28,25,25,45,35,40,3,False
304,281,Kirlia,Psychic,Fairy,38,35,35,65,55,50,3,False
305,282,Gardevoir,Psychic,Fairy,68,65,65,125,115,80,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,3,False
356,325,Spoink,Psychic,NaN,60,25,35,70,80,60,3,False
357,326,Grumpig,Psychic,NaN,80,45,65,90,110,80,3,False
391,358,Chimecho,Psychic,NaN,65,50,70,95,80,65,3,False
394,360,Wynaut,Psychic,NaN,95,23,48,23,48,23,3,False
428,386,DeoxysNormal Forme,Psychic,NaN,50,150,50,150,50,150,3,True
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True
430,386,DeoxysDefense Forme,Psychic,NaN,50,70,160,70,160,90,3,True
431,386,DeoxysSpeed Forme,Psychic,NaN,50,95,90,95,90,180,3,True
481,433,Chingling,Psychic,NaN,45,30,50,65,50,45,4,False
487,439,Mime Jr.,Psychic,Fairy,20,25,45,70,90,60,4,False
526,475,Gallade,Psychic,Fighting,68,125,65,65,115,80,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False
537,480,Uxie,Psychic,NaN,75,75,130,75,130,95,4,True
538,481,Mesprit,Psychic,NaN,80,105,105,105,105,80,4,True
539,482,Azelf,Psychic,NaN,75,125,70,125,70,115,4,True
546,488,Cresselia,Psychic,NaN,120,70,120,75,130,85,4,False
553,494,Victini,Psychic,Fire,100,100,100,100,100,100,5,True
576,517,Munna,Psychic,NaN,76,25,45,67,55,24,5,False
577,518,Musharna,Psychic,NaN,116,55,85,107,95,29,5,False
586,527,Woobat,Psychic,Flying,55,45,43,55,43,72,5,False
587,528,Swoobat,Psychic,Flying,67,57,55,77,55,114,5,False
622,561,Sigilyph,Psychic,Flying,72,58,80,103,80,97,5,False
635,574,Gothita,Psychic,NaN,45,30,50,55,65,45,5,False
636,575,Gothorita,Psychic,NaN,60,45,70,75,85,55,5,False
637,576,Gothitelle,Psychic,NaN,70,55,95,95,110,65,5,False
638,577,Solosis,Psychic,NaN,45,30,40,105,50,20,5,False
639,578,Duosion,Psychic,NaN,65,40,50,125,60,30,5,False
640,579,Reuniclus,Psychic,NaN,110,65,75,125,85,30,5,False
666,605,Elgyem,Psychic,NaN,55,55,55,85,55,30,5,False
667,606,Beheeyem,Psychic,NaN,75,75,75,125,95,40,5,False
745,677,Espurr,Psychic,NaN,62,48,54,63,60,68,6,False
746,678,MeowsticMale,Psychic,NaN,74,48,76,83,81,104,6,False
747,678,MeowsticFemale,Psychic,NaN,74,48,76,83,81,104,6,False
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True